---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "*.md"
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "*.md"
upload_dir: content/images
public_path: "/static/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
